FASTAPI_URL_DOCKER ="http://fastapi:8000/predict"
FASTAPI_URL= "http://localhost:8000/predict"

[postgres]
host = "postgres_airflow"
port = "5432"
database = "ml_project"
user = "ml_user"
password = "ml_pass"
